### ISSUE TITLE
Support for React router v8?

### ISSUE THREAD

**Issue by tahvane1** [rphlmr/react-router-hono-server#234]
Hello,
I tried to upgrade our project to React router v8 but it fails as this project does not support it yet. It is complaining about "Cannot find module 'vite-node/client'" but this is due to older dependency.

Br,
Erkka

**Comment by rphlmr** [comment]
Hi 👋 

Thanks for reporting.

I haven't updated our project at work yet, but I will take a look ASAP.

**Comment by chinfeng** [comment]
My project works with rr8 under dev mode. But not working under build mode. It seems `react-router-hono-server/vite` unable to take over the build process.

**Comment by rphlmr** [comment]
Hey there, you can try the preview version.

```sh
pnpm add https://pkg.pr.new/react-router-hono-server@235
```

A lot has changed with the Vite underlying. If this build works for you, I can release a preview npm one

**Comment by tahvane1** [comment]
I think it is not working (or I have something else broken). When I update project to 8.2.0 development runs okay. But after bundling nothing responds from port.

**Comment by rphlmr** [comment]
> I think it is not working (or I have something else broken). When I update project to 8.2.0 development runs okay. But after bundling nothing responds from port.

:( is it node adapter?

**Comment by tahvane1** [comment]
bun

**Comment by rphlmr** [comment]
Will take a look next week. It was working on my example, but who knows. Some things changed for Bun where it worked instantly for Node.

Sorry for the delay, taking some vacations right now 😇

**Comment by rphlmr** [comment]
new build that should fixes it

```sh
pnpm add https://pkg.pr.new/react-router-hono-server@237
```

**Comment by rphlmr** [comment]
or npm package: https://github.com/rphlmr/react-router-hono-server/releases/tag/v3.0.0-next.0

**Comment by rphlmr** [comment]
Released! https://github.com/rphlmr/react-router-hono-server/releases/tag/v3.0.0
